name: "generate-version-and-release-notes"
description: "generates semver and changelog.md after a pull request has been merge"
inputs:
  user-email:
    description: "email to sign the commit that will be pushed to main branch"
    required: true
  user-name:
    description: "name to sign the commit that will be pushed to main branch"
    required: true
    default: "GitHub Actions"
  skip-git-commit:
    description: "Specify if git commit should be skipped for changed files. Default is false - meaning, files are committed and commit is tagged and pushed"
    required: false
    default: "false"
  version-prefix:
    description: "Prefix to put immediately before the version number when tagging. Example: v0.1.4, beta-1.4.2"
    required: false
    default: ""
  custom-conventional-commits-file:
    description: "json files with the custom conventional commit type vs release type associated. DO NOT PROVIDE WITH ./ AT THE BEGINING"
    required: false
  app-dir:
    description: "app dir where the changelog and version.json will be created"
    required: false

outputs:
  service-version:
    description: 'Service version'
    value: ${{ steps.service-version.outputs.service-version }}

runs:
  using: "composite"
  steps:
    - name: 'Validate Custom Conventional Commit File IF Provided'
      if: ${{ github.event.inputs.custom-conventional-commits-file != '' }}
      run: |
        echo "value:${{ inputs.custom-conventional-commits-file }}"
        node ${{ github.action_path }}/validate-custom-cc-types.js ${{ inputs.custom-conventional-commits-file }}
        echo "USE_CUSTOM_CC=true" >> $GITHUB_ENV
        echo "CUSTOM_CC=$(pwd)/${{ inputs.custom-conventional-commits-file }}" >> $GITHUB_ENV
      shell: bash
    - name: 'Generate Version And Release Notes'
      env:
        DEFAULT_CC: '${{ github.action_path }}/default-conventional-commits-accepted.json'
      run: |
        git config user.email ${{ inputs.user-email }}
        git config user.name ${{ inputs.user-name }}
        if [[ -n "${{ inputs.app-dir }}" ]]; then
          cd ${{ inputs.app-dir }}
        fi
        node ${{ github.action_path }}/generate-version-and-release-notes.js ${{ inputs.skip-git-commit }} ${{ inputs.version-prefix }} $CUSTOM_CC
      shell: bash
    - id: service-version
      run: |
        if [[ -n "${{ inputs.app-dir }}" ]]; then
          cd ${{ inputs.app-dir }}
        fi
        echo "::set-output name=service-version::$(cat ./version.json | jq -r '.version')"
      shell: bash
