name: "generate-version-and-release-notes"
description: "generates semver and changelog.md after a pull request has been merge"
inputs:
  user-email:
    description: "email to sign the commit that will be pushed to main branch"
    required: true
  user-name:
    description: "name to sign the commit that will be pushed to main branch"
    required: true
    default: "GitHub Actions"
  skip-git-commit:
    description: "Specify if git commit should be skipped for changed files. Default is false - meaning, files are committed and commit is tagged and pushed"
    required: false
    default: "false"
  version-prefix:
    description: "Prefix to put immediately before the version number when tagging. Example: v0.1.4, beta-1.4.2"
    required: false
    default: ""
  settings-file:
    description: "json files with the custom conventional commit type vs release type associated. DO NOT PROVIDE WITH ./ AT THE BEGINING"
    required: false
  base-path:
    description: "path where it will be located version and changelog files. DO NOT PROVIDE WITH ./ AT THE BEGINING"
    required: false
  post-script:
    description: "If it is provided the script(js) it will be executed before commit and tag"
    required: false

outputs:
  service-version:
    description: 'Service version'
    value: ${{ steps.service-version.outputs.service-version }}

runs:
  using: "composite"
  steps:
    - name: 'Generate Version And Release Notes'
      id: generate-version-and-release-notes
      env:
        VERSION_PREFIX: ${{ inputs.version-prefix }}
        SETTINGS_FILE: ${{ inputs.settings-file }}
        BASE_PATH: ${{ inputs.base-path }}
      run: |
        node ${{ github.action_path }}/main.js
      shell: bash
    - name: 'Execute Post Script'
      if: ${{ inputs.post-script }}
      env:
        VERSION_PREFIX: ${{ inputs.version-prefix }}
        SETTINGS_FILE: ${{ inputs.settings-file }}
        BASE_PATH: ${{ inputs.base-path }}
        NEW_VERSION: ${{ steps.generate-version-and-release-notes.outputs.new-version }}
      run: |
        node ${{ inputs.post-script }}
      shell: bash
    - name: 'Commit And Tag Version And Release Notes'
      env:
        VERSION_PREFIX: ${{ inputs.version-prefix }}
        SKIP_GIT_COMMIT: ${{ inputs.skip-git-commit }} 
        NEW_VERSION: ${{ steps.generate-version-and-release-notes.outputs.new-version }}
      run: |
        git config user.email ${{ inputs.user-email }}
        git config user.name ${{ inputs.user-name }}
        node ${{ github.action_path }}/commit-and-tag.js
      shell: bash
    - id: service-version
      run: |
        echo "::set-output name=service-version::$(cat ./${{ inputs.base-path }}/version.json | jq -r '.version')"
      shell: bash
