name: continuous-integration
on:
  push:
    branches-ignore:
      - "main"

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Hello world action step
        uses: ohpensource/generate-version-and-release-notes-gh-action@LANZ-2363
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"